apiVersion: v1
kind: ConfigMap
metadata:
  name: reminder-app-config
  namespace: default
data:
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://localstack.cloud.svc.cluster.local:4566"
  ENVIRONMENT_NAME: "dev"
  OPENSEARCH_HOST: "localstack.cloud.svc.cluster.local"
  OPENSEARCH_PORT: "4510"
  OPENSEARCH_HTTPS_PORT: "4510"
  OPENSEARCH_USER: "admin"
  OPENSEARCH_USE_SSL: "false"
  OPENSEARCH_SSL_VERIFICATION_MODE: "none"
  OPENSEARCH_TRUSTSTORE_PATH: "/app/certs/truststore.jks"
  OPENSEARCH_TRUSTSTORE_PASSWORD: "changeit"
  NLP_SERVICE_HOST: "nlp-service.app.svc.cluster.local"
  NLP_SERVICE_PORT: "50051"
  GRPC_USE_TLS: "false"
  WS_PORT: "8090"
  DB_ENABLED: "true"
  DB_HOST: "postgres.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "voice_reminder"
  DB_SCHEMA: "voice_schema"
  DB_POOL_SIZE: "10"
  DB_POOL_MIN_IDLE: "5"
  FLYWAY_ENABLED: "true"
  FLYWAY_BASELINE_VERSION: "1"
  FLYWAY_LOCATIONS: "classpath:db/migration"
  JPA_DDL_GENERATION: "none"
  JPA_SHOW_SQL: "false"
  TOKEN_EXPIRATION: "86400000"
  ISSUER: "voice-reminder-app"
  APP_BASE_URL: "http://localhost:8090"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_SSL: "false"
  SMTP_TLS: "true"
  SMTP_AUTH: "true"
  SMTP_STARTTLS: "true"
  REDIS_HOST: "redis.database.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_TIMEOUT: "5000"
  REDIS_MAX_TOTAL: "50"
  REDIS_MAX_IDLE: "10"
  REDIS_MIN_IDLE: "5"
  REDIS_USE_SSL: "true"
  REDIS_SSL_TRUSTSTORE_PASSWORD: "changeit"
  REDIS_SSL_KEYSTORE_PASSWORD: "changeit"
  REDIS_SSL_TRUSTSTORE_PATH: "/app/redis_certs/redis_truststore.jks"
  REDIS_SSL_KEYSTORE_PATH: "/app/redis_certs/redis_keystore.jks"
  REDIS_SSL_VERIFY_MODE: "full"
  REDIS_SSL_PROTOCOL: "TLSv1.2"
  REDIS_SSL_ENABLED_PROTOCOLS: "TLSv1.2,TLSv1.3"
  REDIS_SSL_CIPHER_SUITES: "TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256"
  JAVA_OPTS: "-Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Xmx512m -Xms256m"