apiVersion: v1
kind: Secret
metadata:
  name: reminder-app-secrets
  namespace: default
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  OPENSEARCH_ADMIN_PASSWORD: ${OPENSEARCH_ADMIN_PASSWORD}
  NLP_GRPC_API_KEY: ${NLP_GRPC_API_KEY}
  SECRET_KEY: ${SECRET_KEY}
  SMTP_USERNAME: "losik2006@gmail.com"
  SMTP_PASSWORD: ${SMTP_PASSWORD}
  FROM_EMAIL: "losik2006@gmail.com"
  REDIS_PASSWORD: ${REDIS_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: reminder-app-files
  namespace: default
type: Opaque
data:
  jwt_secret: ${JWT_SECRET_BASE64}