apiVersion: v1
kind: Service
metadata:
  name: reminder-app
  namespace: app
  labels:
    app: reminder-app
    component: backend
spec:
  selector:
    app: reminder-app
  ports:
    - port: 8090
      targetPort: 8090
      name: http
  type: ClusterIP