apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: cloud

secretGenerator:
  - name: cloud-env-secrets
    namespace: cloud
    literals:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - OPENSEARCH_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}

configMapGenerator:
  - name: cloud-env-config
    namespace: cloud
    literals:
      - AWS_REGION=${AWS_REGION}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}

replacements:
  - source:
      kind: Secret
      name: cloud-env-secrets
      fieldPath: data.OPENSEARCH_ADMIN_PASSWORD
    targets:
      - select:
          kind: Secret
          name: .*localstack.*
        fieldPaths:
          - stringData.OPENSEARCH_ADMIN_PASSWORD
          - stringData.opensearch_password.txt
        options:
          create: true

  - source:
      kind: Secret
      name: cloud-env-secrets
      fieldPath: data.AWS_ACCESS_KEY_ID
    targets:
      - select:
          kind: Secret
          name: .*localstack.*
        fieldPaths:
          - stringData.AWS_ACCESS_KEY_ID
          - stringData.aws_access_key.txt
        options:
          create: true

  - source:
      kind: Secret
      name: cloud-env-secrets
      fieldPath: data.AWS_SECRET_ACCESS_KEY
    targets:
      - select:
          kind: Secret
          name: .*localstack.*
        fieldPaths:
          - stringData.AWS_SECRET_ACCESS_KEY
          - stringData.aws_secret_key.txt
        options:
          create: true

  - source:
      kind: Secret
      name: cloud-env-secrets
      fieldPath: data.LOCALSTACK_API_KEY
    targets:
      - select:
          kind: Secret
          name: .*localstack.*
        fieldPaths:
          - stringData.LOCALSTACK_API_KEY
        options:
          create: true

  - source:
      kind: Secret
      name: cloud-env-secrets
      fieldPath: data.OPENSEARCH_ROOT_CA
      targets:
        - select:
            kind: Secret
            name: .*opensearch-certs.*
            namespace: cloud
          fieldPaths:
            - stringData.root-ca.pem
          options:
            create: true

  - source:
      kind: Secret
      name: cloud-env-secrets
      fieldPath: data.OPENSEARCH_NODE_CERT
    targets:
      - select:
          kind: Secret
          name: .*opensearch-certs.*
          namespace: cloud
        fieldPaths:
          - stringData.node.pem
        options:
          create: true

  - source:
      kind: Secret
      name: cloud-env-secrets
      fieldPath: data.OPENSEARCH_NODE_KEY
    targets:
      - select:
          kind: Secret
          name: .*opensearch-certs.*
          namespace: cloud
        fieldPaths:
          - stringData.node-key.pem
        options:
          create: true

  - source:
      kind: Secret
      name: cloud-env-secrets
      fieldPath: data.OPENSEARCH_ADMIN_CERT
    targets:
      - select:
          kind: Secret
          name: .*opensearch-certs.*
          namespace: cloud
        fieldPaths:
          - stringData.admin.pem
        options:
          create: true

  - source:
      kind: Secret
      name: cloud-env-secrets
      fieldPath: data.OPENSEARCH_ADMIN_KEY
    targets:
      - select:
          kind: Secret
          name: .*opensearch-certs.*
          namespace: cloud
        fieldPaths:
          - stringData.admin-key.pem
        options:
          create: true