apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: database

secretGenerator:
  - name: db-env-secrets
    namespace: database
    literals:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD_URLENCODED=${POSTGRES_PASSWORD_URLENCODED}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_KEY_PEM=${REDIS_KEY_PEM}
      - REDIS_CERT_PEM=${REDIS_CERT_PEM}
      - REDIS_CA_PEM=${REDIS_CA_PEM}

configMapGenerator:
  - name: db-env-config
    namespace: database
    literals:
      - POSTGRES_DB=${POSTGRES_DB}

replacements:
  - source:
      kind: Secret
      name: db-env-secrets
      fieldPath: data.POSTGRES_USER
    targets:
      - select:
          kind: Secret
          name: .*postgres.*
        fieldPaths:
          - stringData.POSTGRES_USER
          - stringData.postgres_user.txt
        options:
          create: true

  - source:
      kind: Secret
      name: db-env-secrets
      fieldPath: data.POSTGRES_PASSWORD
    targets:
      - select:
          kind: Secret
          name: .*postgres.*
        fieldPaths:
          - stringData.POSTGRES_PASSWORD
          - stringData.postgres_password.txt
          - stringData.postgres_password
        options:
          create: true

  - source:
      kind: ConfigMap
      name: db-env-config
      fieldPath: data.POSTGRES_DB
    targets:
      - select:
          kind: Secret
          name: .*postgres.*
        fieldPaths:
          - stringData.POSTGRES_DB
          - stringData.postgres_db.txt
        options:
          create: true

  - source:
      kind: Secret
      name: db-env-secrets
      fieldPath: data.REDIS_PASSWORD
    targets:
      - select:
          kind: Secret
          name: .*redis.*
        fieldPaths:
          - stringData.REDIS_PASSWORD
        options:
          create: true

  - source:
      kind: Secret
      name: db-env-secrets
      fieldPath: data.REDIS_KEY_PEM
    targets:
      - select:
          kind: Secret
          name: .*redis-certs.*
        fieldPaths:
          - stringData.redis-key.pem
        options:
          create: true

  - source:
      kind: Secret
      name: db-env-secrets
      fieldPath: data.REDIS_CERT_PEM
    targets:
      - select:
          kind: Secret
          name: .*redis-certs.*
        fieldPaths:
          - stringData.redis.pem
        options:
          create: true

  - source:
      kind: Secret
      name: db-env-secrets
      fieldPath: data.REDIS_CA_PEM
    targets:
      - select:
          kind: Secret
          name: .*redis-certs.*
        fieldPaths:
          - stringData.root-ca.pem
        options:
          create: true