apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: monitoring

secretGenerator:
  - name: monitoring-env-secrets
    namespace: monitoring
    literals:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD_URLENCODED=${POSTGRES_PASSWORD_URLENCODED}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - GRAFANA_USER=${GRAFANA_USER}
      - GRAFANA_PASSWORD=${GRAFANA_PASSWORD}
      - REDIS_KEY_PEM=${REDIS_KEY_PEM}
      - REDIS_CERT_PEM=${REDIS_CERT_PEM}
      - REDIS_CA_PEM=${REDIS_CA_PEM}

configMapGenerator:
  - name: monitoring-env-config
    namespace: monitoring
    literals:
      - AWS_REGION=${AWS_REGION}
      - AWS_ENDPOINT_URL=${AWS_ENDPOINT_URL}

replacements:
  - source:
      kind: Secret
      name: monitoring-env-secrets
      fieldPath: data.POSTGRES_PASSWORD_URLENCODED
    targets:
      - select:
          kind: Secret
          name: .*postgres-exporter.*
        fieldPaths:
          - stringData.DATA_SOURCE_NAME
        options:
          create: true
    template: |
      postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD_URLENCODED}@postgres.database:5432/${POSTGRES_DB}?sslmode=disable

  - source:
      kind: Secret
      name: monitoring-env-secrets
      fieldPath: data.REDIS_PASSWORD
    targets:
      - select:
          kind: Secret
          name: .*redis-exporter.*
        fieldPaths:
          - stringData.REDIS_PASSWORD
        options:
          create: true

  - source:
      kind: Secret
      name: monitoring-env-secrets
      fieldPath: data.GRAFANA_USER
    targets:
      - select:
          kind: Secret
          name: .*grafana.*
        fieldPaths:
          - stringData.GF_SECURITY_ADMIN_USER
        options:
          create: true

  - source:
      kind: Secret
      name: monitoring-env-secrets
      fieldPath: data.GRAFANA_PASSWORD
    targets:
      - select:
          kind: Secret
          name: .*grafana.*
        fieldPaths:
          - stringData.GF_SECURITY_ADMIN_PASSWORD
        options:
          create: true

  - source:
      kind: Secret
      name: monitoring-env-secrets
      fieldPath: data.AWS_ACCESS_KEY_ID
    targets:
      - select:
          kind: Secret
          name: .*cloudwatch-exporter.*
        fieldPaths:
          - stringData.AWS_ACCESS_KEY_ID
        options:
          create: true

  - source:
      kind: Secret
      name: monitoring-env-secrets
      fieldPath: data.AWS_SECRET_ACCESS_KEY
    targets:
      - select:
          kind: Secret
          name: .*cloudwatch-exporter.*
        fieldPaths:
          - stringData.AWS_SECRET_ACCESS_KEY
        options:
          create: true

  - source:
      kind: ConfigMap
      name: monitoring-env-config
      fieldPath: data.AWS_REGION
    targets:
      - select:
          kind: Secret
          name: .*cloudwatch-exporter.*
        fieldPaths:
          - stringData.AWS_REGION
        options:
          create: true

  - source:
      kind: ConfigMap
      name: monitoring-env-config
      fieldPath: data.AWS_ENDPOINT_URL
    targets:
      - select:
          kind: Secret
          name: .*cloudwatch-exporter.*
        fieldPaths:
          - stringData.AWS_ENDPOINT_URL
        options:
          create: true

  - source:
      kind: Secret
      name: monitoring-env-secrets
      fieldPath: data.REDIS_KEY_PEM
    targets:
      - select:
          kind: Secret
          name: .*redis-certs.*
        fieldPaths:
          - stringData.redis-key.pem
        options:
          create: true

  - source:
      kind: Secret
      name: monitoring-env-secrets
      fieldPath: data.REDIS_CERT_PEM
    targets:
      - select:
          kind: Secret
          name: .*redis-certs.*
        fieldPaths:
          - stringData.redis.pem
        options:
          create: true

  - source:
      kind: Secret
      name: monitoring-env-secrets
      fieldPath: data.REDIS_CA_PEM
    targets:
      - select:
          kind: Secret
          name: .*redis-certs.*
        fieldPaths:
          - stringData.root-ca.pem
        options:
          create: true

  - source:
      kind: Secret
      name: monitoring-env-secrets
      fieldPath: data.OPENSEARCH_ROOT_CA
    targets:
      - select:
          kind: Secret
          name: .*opensearch-certs.*
          namespace: monitoring
        fieldPaths:
          - stringData.root-ca.pem
        options:
          create: true