apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: env-vars
  namespace: app
literals:
  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - POSTGRES_USER=${POSTGRES_USER}
  - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  - OPENSEARCH_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
  - NLP_GRPC_API_KEY=${NLP_GRPC_API_KEY}
  - JWT_SECRET=${JWT_SECRET}
  - SMTP_USERNAME=${SMTP_USERNAME}
  - SMTP_PASSWORD=${SMTP_PASSWORD}
  - FROM_EMAIL=${FROM_EMAIL}
  - REDIS_PASSWORD=${REDIS_PASSWORD}