apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudwatch-exporter
  namespace: monitoring
  labels:
    app: cloudwatch-exporter
    component: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudwatch-exporter
  template:
    metadata:
      labels:
        app: cloudwatch-exporter
        component: monitoring
    spec:
      serviceAccountName: cloudwatch-exporter-sa
      containers:
        - name: cloudwatch-exporter
          image: pyrodocker1/reminder-cloudwatch-exporter:1.0
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: cloudwatch-exporter-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudwatch-exporter-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: cloudwatch-exporter-secrets
                  key: AWS_REGION
            - name: AWS_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: cloudwatch-exporter-secrets
                  key: AWS_ENDPOINT_URL
          ports:
            - containerPort: 9106
              name: metrics
          volumeMounts:
            - name: config
              mountPath: /app/config.yml
              subPath: config.yml
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: config
          configMap:
            name: cloudwatch-exporter-config