apiVersion: v1
kind: Service
metadata:
  name: cloudwatch-exporter
  namespace: monitoring
  labels:
    app: cloudwatch-exporter
    component: exporter
    aws-service: cloudwatch
spec:
  selector:
    app: cloudwatch-exporter
  ports:
    - port: 9106
      targetPort: 9106
      name: metrics
  type: ClusterIP