apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets/

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: voice-reminder

commonAnnotations:
  app.kubernetes.io/version: 1.0.0