apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: database
data:
  redis.conf: |
    bind 0.0.0.0
    port 6380
    tls-port 6379

    tls-cert-file /usr/local/etc/redis/certs/redis.pem
    tls-key-file /usr/local/etc/redis/certs/redis-key.pem
    tls-ca-cert-file /usr/local/etc/redis/certs/root-ca.pem
    tls-auth-clients optional
    tls-protocols "TLSv1.2 TLSv1.3"
    tls-ciphers "DEFAULT:@SECLEVEL=1"
    tls-session-caching yes
    tls-session-cache-timeout 300
    tls-prefer-server-ciphers yes

    save 60 1
    appendonly yes
    appendfsync everysec

    maxmemory 256mb
    maxmemory-policy allkeys-lru

    loglevel notice;