apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: localstack-role
  namespace: cloud
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: localstack-binding
  namespace: cloud
subjects:
  - kind: ServiceAccount
    name: localstack-sa
    namespace: cloud
roleRef:
  kind: Role
  name: localstack-role
  apiGroup: rbac.authorization.k8s.io