apiVersion: v1
kind: ServiceAccount
metadata:
  name: reminder-app-sa
  namespace: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nlp-service-sa
  namespace: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dlq-processor-sa
  namespace: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama-sa
  namespace: app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: localstack-sa
  namespace: cloud
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-sa
  namespace: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cadvisor-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-exporter-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-exporter-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-exporter-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatch-exporter-sa
  namespace: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opensearch-exporter-sa
  namespace: monitoring