version: '3.8'

services:
  nlp-service:
    image: pyrodocker1/reminder-nlp:1.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment:
      - MODEL_DIR=/app/models
      - INTENT_MODEL_PATH=/app/models/intent_classifier
      - NER_MODEL_PATH=/app/models/ner_model
      - LOG_LEVEL=INFO
      - GRPC_PORT=50051
      - GRPC_USE_TLS=true
      - NLP_GRPC_API_KEY=${NLP_GRPC_API_KEY:-QxqNj6thFFqzWQe7xPEmynIjjdnkP4bf44RP0dZKbYE=}
    secrets:
      - source: nlp_grpc_key
        target: /run/secrets/nlp_grpc_key.txt
    volumes:
      - type: bind
        source: ./nlp/models
        target: /app/models
      - type: bind
        source: ./nlp/data
        target: /app/data
      - type: bind
        source: ./nlp/nlp_service
        target: /app/nlp_service
      - type: bind
        source: ./nlp/proto
        target: /app/proto
    networks:
      - reminder-network
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  localstack:
    image: localstack/localstack:4.12
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 300s
    environment:
      - SERVICES=lambda,s3,events,opensearch,ses,transcribe,sns,sqs,iam,cloudformation,cloudwatch,logs,eventbridge,secretsmanager,secretsmanager_v2,acm,apigateway,route53
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=0
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY:-}
      - OPENSEARCH_ENDPOINT_STRATEGY=port
      - OPENSEARCH_PORT=4510
      - OPENSEARCH_HOST=0.0.0.0
      - OPENSEARCH_PORT_EXTERNAL=4510
      - OPENSEARCH_HTTPS_PORT=4510
      - OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m -Des.path.data=/tmp/opensearch_data -Des.path.logs=/tmp/opensearch_logs
      - INIT_SCRIPTS_PATH=/etc/localstack/init/ready.d/
      - OPENSEARCH_ENABLE_SECURITY=true
      - OPENSEARCH_ENABLE_SSL=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - OPENSEARCH_PLUGINS_LIST=opensearch-security
      - DISABLE_OPENSEARCH_SECURITY_PLUGIN=false
      - OPENSEARCH_NODE_TO_NODE_ENCRYPTION=true
      - OPENSEARCH_SSL_CERTIFICATE_PATH=/etc/localstack/opensearch/certs/node.pem
      - OPENSEARCH_SSL_KEY_PATH=/etc/localstack/opensearch/certs/node-key.pem
      - OPENSEARCH_ROOT_CA_PATH=/etc/localstack/opensearch/certs/root-ca.pem
      - OPENSEARCH_ADMIN_CERTIFICATE_PATH=/etc/localstack/opensearch/certs/admin.pem
      - OPENSEARCH_ADMIN_KEY_PATH=/etc/localstack/opensearch/certs/admin-key.pem
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./localstack_data
        target: /var/lib/localstack
      - type: bind
        source: ./aws-init.sh
        target: /etc/localstack/init/ready.d/init.sh
      - type: bind
        source: ./template.yaml
        target: /etc/localstack/init/ready.d/template.yaml
      - type: bind
        source: ./opensearch_certs
        target: /etc/localstack/opensearch/certs
        read_only: true
    networks:
      - reminder-network
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -k http://localhost:4510/ > /dev/null"]
      interval: 20s
      timeout: 15s
      retries: 10
      start_period: 90s

  postgres:
    image: postgres:15-alpine
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    environment:
      POSTGRES_DB: voice_reminder
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --encoding=UTF8"
      POSTGRES_INITDB_WALDIR: /var/lib/postgresql/pg_wal
      TZ: UTC
    secrets:
      - source: postgres_password
        target: /run/secrets/postgres_password.txt
        mode: 0440
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./postgres-init
        target: /docker-entrypoint-initdb.d
    networks:
      - reminder-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d voice_reminder" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: >
      postgres 
      -c max_connections=200 
      -c shared_buffers=256MB 
      -c effective_cache_size=1GB 
      -c maintenance_work_mem=64MB 
      -c checkpoint_completion_target=0.9 
      -c wal_buffers=16MB 
      -c default_statistics_target=100
      -c random_page_cost=1.1 
      -c effective_io_concurrency=200 
      -c work_mem=4MB 
      -c min_wal_size=1GB 
      -c max_wal_size=4GB

  reminder-app:
    image: pyrodocker1/reminder-backend:1.0
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - ENVIRONMENT_NAME=dev
      - USE_LOCAL_SECRETS=true
      - SECRETS_PATH=/run/secrets
      - JAVA_OPTS=-Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Xmx512m -Xms256m
      - OPENSEARCH_HOST=localstack
      - OPENSEARCH_PORT=4510
      - OPENSEARCH_USER=admin
      - OPENSEARCH_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - OPENSEARCH_USE_SSL=false
      - OPENSEARCH_SSL_VERIFICATION_MODE=none
      - OPENSEARCH_TRUSTSTORE_PATH=/app/certs/truststore.jks
      - OPENSEARCH_TRUSTSTORE_PASSWORD=changeit
      - NLP_SERVICE_HOST=nlp-service
      - NLP_SERVICE_PORT=50051
      - WS_PORT=8090
      - DB_ENABLED=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=voice_reminder
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_SCHEMA=voice_schema
      - DB_POOL_SIZE=10
      - DB_POOL_MIN_IDLE=5
      - FLYWAY_ENABLED=true
      - FLYWAY_BASELINE_VERSION=1
      - FLYWAY_LOCATIONS=classpath:db/migration,filesystem:/app/db/migration
      - JPA_DDL_GENERATION=none
      - JPA_SHOW_SQL=false
    secrets:
      - source: postgres_password
        target: /run/secrets/postgres_password.txt
        mode: 0440
    volumes:
      - type: bind
        source: ./web
        target: /app/web
      - type: bind
        source: ./secrets/application.properties
        target: /app/config/application.properties
        read_only: true
      - type: bind
        source: ./opensearch_certs
        target: /app/certs
        read_only: true
      - type: bind
        source: ./db/migration
        target: /app/db/migration
        read_only: true
    networks:
      - reminder-network
    depends_on:
      - nlp-service
      - localstack
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/health"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 120s

secrets:
  nlp_grpc_key:
    file: ./secrets/nlp_grpc_key.txt
  postgres_password:
    file: ./secrets/postgres_password.txt

networks:
  reminder-network:
    driver: overlay
    attachable: true

volumes:
  postgres_data:
    driver: local
  nlp_models:
    driver: local
  nlp_data:
    driver: local