version: '3.8'

services:
  traefik:
    image: traefik:v3
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--ping=true"
      - "--ping.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    networks:
      - reminder-network

  nfs-server:
    image: itsthenetwork/nfs-server-alpine:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.nfs == true
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 64M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 30s
    ports:
      - target: 2049
        published: 2049
        protocol: tcp
        mode: host
      - target: 111
        published: 111
        protocol: tcp
        mode: host
      - target: 2049
        published: 2049
        protocol: udp
        mode: host
      - target: 111
        published: 111
        protocol: udp
        mode: host
    volumes:
      - type: bind
        source: /nfs-storage
        target: /exports
      - type: bind
        source: ./nfs-config/exports
        target: /etc/exports
        read_only: true
    environment:
      - SHARED_DIRECTORY=/exports
      - NFS_VERSION=4
      - DISABLE_ACCESS_CONTROL=true
    networks:
      reminder-network:
        aliases:
          - nfs.internal
    healthcheck:
      test: ["CMD", "rpcinfo", "-p", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=false"

  nlp-service:
    image: pyrodocker1/reminder-nlp:1.0
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      - MODEL_DIR=/app/models
      - INTENT_MODEL_PATH=/app/models/intent_classifier
      - NER_MODEL_PATH=/app/models/ner_model
      - LOG_LEVEL=INFO
      - GRPC_PORT=50051
      - GRPC_USE_TLS=true
    secrets:
      - source: nlp_grpc_key
        target: /run/secrets/nlp_grpc_key.txt
        mode: 0440
    volumes:
      - type: volume
        source: nfs_nlp_models
        target: /app/models
      - type: volume
        source: nfs_nlp_data
        target: /app/data
      - type: bind
        source: ./nlp/nlp_service
        target: /app/nlp_service
      - type: bind
        source: ./nlp/proto
        target: /app/proto
    networks:
      - reminder-network
    healthcheck:
      test: ["CMD", "python", "-c", "import grpc; import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=false"

  localstack:
    image: localstack/localstack:4.12
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 3G
        reservations:
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 300s
    environment:
      - SERVICES=lambda,s3,events,opensearch,ses,transcribe,sns,sqs,iam,cloudformation,cloudwatch,logs,eventbridge,secretsmanager,secretsmanager_v2,acm,apigateway,route53
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY:-}
      - OPENSEARCH_ENDPOINT_STRATEGY=port
      - OPENSEARCH_PORT=4510
      - OPENSEARCH_HOST=0.0.0.0
      - OPENSEARCH_PORT_EXTERNAL=4510
      - OPENSEARCH_HTTPS_PORT=4510
      - OPENSEARCH_JAVA_OPTS=-Xms256m -Xmx256m -Des.path.data=/tmp/opensearch_data -Des.path.logs=/tmp/opensearch_logs
      - INIT_SCRIPTS_PATH=/etc/localstack/init/ready.d/
      - OPENSEARCH_ENABLE_SECURITY=true
      - OPENSEARCH_ENABLE_SSL=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD_FILE=/run/secrets/opensearch_password.txt
      - OPENSEARCH_PLUGINS_LIST=opensearch-security
      - DISABLE_OPENSEARCH_SECURITY_PLUGIN=false
      - OPENSEARCH_NODE_TO_NODE_ENCRYPTION=true
      - OPENSEARCH_SSL_CERTIFICATE_PATH=/etc/localstack/opensearch/certs/node.pem
      - OPENSEARCH_SSL_KEY_PATH=/etc/localstack/opensearch/certs/node-key.pem
      - OPENSEARCH_ROOT_CA_PATH=/etc/localstack/opensearch/certs/root-ca.pem
      - OPENSEARCH_ADMIN_CERTIFICATE_PATH=/etc/localstack/opensearch/certs/admin.pem
      - OPENSEARCH_ADMIN_KEY_PATH=/etc/localstack/opensearch/certs/admin-key.pem
    secrets:
      - source: opensearch_password
        target: /run/secrets/opensearch_password.txt
        mode: 0440
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: nfs_localstack_data
        target: /var/lib/localstack
      - type: bind
        source: ./aws-init.sh
        target: /etc/localstack/init/ready.d/init.sh
      - type: bind
        source: ./template.yaml
        target: /etc/localstack/init/ready.d/template.yaml
      - type: bind
        source: ./opensearch_certs
        target: /etc/localstack/opensearch/certs
        read_only: true
    networks:
      - reminder-network
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -k http://localhost:4510/ > /dev/null"]
      interval: 20s
      timeout: 15s
      retries: 10
      start_period: 90s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.localstack.rule=Host(`localstack.reminder.local`)"
      - "traefik.http.routers.localstack.entrypoints=web"
      - "traefik.http.services.localstack.loadbalancer.server.port=4566"
      - "traefik.http.routers.localstack.service=localstack"

  postgres:
    image: postgres:15-alpine
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
          - node.labels.postgres == true
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      POSTGRES_DB: voice_reminder
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password.txt
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --encoding=UTF8"
      POSTGRES_INITDB_WALDIR: /var/lib/postgresql/pg_wal
      TZ: UTC
    secrets:
      - source: postgres_password
        target: /run/secrets/postgres_password.txt
        mode: 0440
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
      - type: volume
        source: nfs_postgres_backup
        target: /backup
      - type: bind
        source: ./postgres-init
        target: /docker-entrypoint-initdb.d
    networks:
      - reminder-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d voice_reminder" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: >
      postgres 
      -c max_connections=200 
      -c shared_buffers=256MB 
      -c effective_cache_size=1GB 
      -c maintenance_work_mem=64MB 
      -c checkpoint_completion_target=0.9 
      -c wal_buffers=16MB 
      -c default_statistics_target=100
      -c random_page_cost=1.1 
      -c effective_io_concurrency=200 
      -c work_mem=4MB 
      -c min_wal_size=1GB 
      -c max_wal_size=4GB
    labels:
      - "traefik.enable=false"

  reminder-app:
    image: pyrodocker1/reminder-backend:1.1-1
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - ENVIRONMENT_NAME=dev
      - USE_LOCAL_SECRETS=true
      - SECRETS_PATH=/run/secrets
      - JAVA_OPTS=-Dfile.encoding=UTF-8 -Dconsole.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Xmx512m -Xms256m
      - OPENSEARCH_HOST=localstack
      - OPENSEARCH_PORT=4510
      - OPENSEARCH_HTTPS_PORT=4510
      - OPENSEARCH_USER=admin
      - OPENSEARCH_ADMIN_PASSWORD=${OPENSEARCH_ADMIN_PASSWORD}
      - OPENSEARCH_USE_SSL=false
      - OPENSEARCH_SSL_VERIFICATION_MODE=none
      - OPENSEARCH_TRUSTSTORE_PATH=/app/certs/truststore.jks
      - OPENSEARCH_TRUSTSTORE_PASSWORD=changeit
      - NLP_SERVICE_HOST=nlp-service
      - NLP_SERVICE_PORT=50051
      - WS_PORT=8090
      - DB_ENABLED=true
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=voice_reminder
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_SCHEMA=voice_schema
      - DB_POOL_SIZE=10
      - DB_POOL_MIN_IDLE=5
      - FLYWAY_ENABLED=true
      - FLYWAY_BASELINE_VERSION=1
      - FLYWAY_LOCATIONS=classpath:db/migration
      - JPA_DDL_GENERATION=none
      - JPA_SHOW_SQL=false
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=${SMTP_MAIL:-losik2006@gmail.com}
      - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      - FROM_EMAIL=${SMTP_MAIL:-losik2006@gmail.com}
      - SMTP_SSL=false
      - SMTP_TLS=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_TIMEOUT=5000
      - REDIS_MAX_TOTAL=50
      - REDIS_MAX_IDLE=10
      - REDIS_MIN_IDLE=5
      - REDIS_USE_SSL=true
      - REDIS_SSL_TRUSTSTORE_PASSWORD=changeit
      - REDIS_SSL_KEYSTORE_PASSWORD=changeit
      - REDIS_SSL_TRUSTSTORE_PATH=/app/redis_certs/redis_truststore.jks
      - REDIS_SSL_KEYSTORE_PATH=/app/redis_certs/redis_keystore.jks
      - REDIS_SSL_VERIFY_MODE=full
      - REDIS_SSL_PROTOCOL=TLSv1.2
      - REDIS_SSL_ENABLED_PROTOCOLS=TLSv1.2,TLSv1.3
      - REDIS_SSL_CIPHER_SUITES=TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256
    volumes:
      - type: volume
        source: nfs_app_static
        target: /app/web/static
      - type: bind
        source: ./secrets/application.properties
        target: /app/config/application.properties
        read_only: true
      - type: bind
        source: ./opensearch_certs
        target: /app/certs
        read_only: true
      - type: bind
        source: ./db/migration
        target: /app/db/migration
        read_only: true
      - type: bind
        source: ./redis/certs
        target: /app/redis_certs
        read_only: true
    networks:
      - reminder-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/test"]
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.reminder-app.rule=Host(`reminder.local`) || Host(`app.reminder.local`)"
      - "traefik.http.routers.reminder-app.entrypoints=web"
      - "traefik.http.services.reminder-app.loadbalancer.server.port=8090"
      - "traefik.http.services.reminder-app.loadbalancer.healthcheck.path=/api/test"
      - "traefik.http.services.reminder-app.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.routers.reminder-app.service=reminder-app"

  portainer:
    image: portainer/portainer-ce:alpine-sts
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 30s
        order: start-first
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: portainer_data
        target: /data
    networks:
      - reminder-network
    labels:
      - "traefik.enable=false"
      - "traefik.docker.lbswarm=false"
      - "traefik.tags=exclude"

  redis:
    image: redis:7-alpine
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --requirepass
      - "${REDIS_PASSWORD}"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    secrets:
      - source: redis_password
        target: /run/secrets/redis_password.txt
        mode: 0440
    volumes:
      - type: bind
        source: ./redis/config/redis.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
      - type: bind
        source: ./redis/certs
        target: /usr/local/etc/redis/certs
        read_only: true
    ports:
      - "6379:6379"
      - "6380:6380"
    networks:
      - reminder-network
    healthcheck:
      test: ["CMD", "redis-cli", "--tls", "--cacert", "/usr/local/etc/redis/certs/root-ca.pem", "--pass", "${REDIS_PASSWORD}", "ping"]  # Исправлен healthcheck
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    labels:
      - "traefik.enable=false"

secrets:
  nlp_grpc_key:
    file: ./secrets/nlp_grpc_key.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  redis_password:
    file: ./secrets/redis_password.txt
  opensearch_password:
    file: ./secrets/opensearch_password.txt

networks:
  reminder-network:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.10.0.0/24

volumes:
  postgres_data:
    driver: local
  portainer_data:
    driver: local

  nfs_nlp_models:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=nfs-server,nolock,soft,rw,timeo=600,retrans=2,vers=4
      device: ":/exports/nlp_models"

  nfs_nlp_data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=nfs-server,nolock,soft,rw,timeo=600,retrans=2,vers=4
      device: ":/exports/nlp_data"

  nfs_localstack_data:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=nfs-server,nolock,soft,rw,timeo=600,retrans=2,vers=4
      device: ":/exports/localstack_data"

  nfs_postgres_backup:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=nfs-server,nolock,soft,rw,timeo=600,retrans=2,vers=4
      device: ":/exports/postgres_backup"

  nfs_app_static:
    driver: local
    driver_opts:
      type: nfs4
      o: addr=nfs-server,nolock,soft,rw,timeo=600,retrans=2,vers=4
      device: ":/exports/app_static"

# export $(cat .env | xargs) && docker stack deploy -c docker-stack.yml swarm