name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}

      - name: Start LocalStack and wait for init
        run: |
          docker-compose up -d localstack postgres redis
          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:4566/_localstack/health)" != "200" ]]; do sleep 5; done'
          sleep 60

      - name: Run Backend Tests
        run: ./gradlew test

      - name: Run NLP Tests
        working-directory: ./nlp
        run: |
          python -m pip install -r requirements.txt

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Backend
        run: ./gradlew shadowJar

      - name: Build NLP Service
        working-directory: ./nlp
        run: docker build -t reminder-nlp:latest .

      - name: Build DLQ Processor
        working-directory: ./dlq-processor
        run: ./gradlew shadowJar && docker build -t reminder-dlq:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Images
        run: |
          docker tag reminder-nlp:latest pyrodocker1/reminder-nlp:${{ github.sha }}
          docker push pyrodocker1/reminder-nlp:${{ github.sha }}

  deploy-swarm:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SWARM_SSH_KEY }}

      - name: Deploy to Swarm
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SWARM_USER }}@${{ secrets.SWARM_HOST }} ' '
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            export TAG=$GITHUB_SHA
            docker stack deploy -c docker-stack.yml swarm --with-registry-auth
          '