AWSTemplateFormatVersion: '2010-09-09'
Description: Voice Reminder

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name

  EmailAddress:
    Type: String
    Default: notifications@example.com
    Description: Email address for sending reminders

  OpenSearchDomainName:
    Type: String
    Default: reminder-domain
    Description: OpenSearch domain name

  S3BucketName:
    Type: String
    Default: voice-reminder-audio-bucket
    Description: S3 bucket for audio files

  LambdaFunctionName:
    Type: String
    Default: send-reminder-lambda
    Description: Lambda function name

Resources:
  AudioBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldAudio
            Status: Enabled
            ExpirationInDays: 30

  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: !Ref OpenSearchDomainName
      EngineVersion: "OpenSearch_2.5"
      ClusterConfig:
        InstanceType: "t3.small.search"
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: true
        VolumeType: "gp2"
        VolumeSize: 10
      SnapshotOptions:
        AutomatedSnapshotStartHour: 2

  TranscribeServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-transcribe-service-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: transcribe.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: TranscribeS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${AudioBucket}
                  - !Sub arn:aws:s3:::${AudioBucket}/*
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub arn:aws:s3:::${AudioBucket}/transcriptions/*

  AppExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-reminder-app-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppReminderPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${AudioBucket}
                  - !Sub arn:aws:s3:::${AudioBucket}/*

              - Effect: Allow
                Action:
                  - transcribe:StartTranscriptionJob
                  - transcribe:GetTranscriptionJob
                  - transcribe:ListTranscriptionJobs
                Resource: "*"

              - Effect: Allow
                Action:
                  - events:PutRule
                  - events:PutTargets
                  - events:EnableRule
                  - events:DisableRule
                  - events:ListRules
                Resource: "*"

              - Effect: Allow
                Action:
                  - es:ESHttpPost
                  - es:ESHttpGet
                  - es:ESHttpPut
                  - es:ESHttpDelete
                Resource: !Sub arn:aws:es:*:*:domain/${OpenSearchDomain}/*

              - Effect: Allow
                Action:
                  - ses:VerifyEmailIdentity
                  - ses:SendEmail
                Resource: "*"

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

              - Effect: Allow
                Action: iam:PassRole
                Resource: !GetAtt TranscribeServiceRole.Arn

              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - secretsmanager:DescribeSecret
                  - secretsmanager:ListSecrets
                Resource: !Ref SecretsManagerSecret

              - Effect: Allow
                Action:
                  - kms:Decrypt
                  - kms:GenerateDataKey
                Resource: !GetAtt KMSCustomerManagedKey.Arn

  ReminderDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${EnvironmentName}-reminder-dlq
      MessageRetentionPeriod: 1209600

  ReminderProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${EnvironmentName}-reminder-queue
      VisibilityTimeout: 300
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ReminderDeadLetterQueue.Arn
        maxReceiveCount: 3

  DLQMessageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-dlq-has-messages
      AlarmDescription: "Messages in Dead Letter Queue require attention"
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ReminderDeadLetterQueue.QueueName
      AlarmActions:
        - !Ref ReminderNotificationTopic
      OKActions:
        - !Ref ReminderNotificationTopic
      InsufficientDataActions:
        - !Ref ReminderNotificationTopic

  DLQOldMessageAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-dlq-old-messages
      AlarmDescription: "Messages have been in DLQ for too long"
      Metrics:
        - Id: m1
          Label: "ApproximateAgeOfOldestMessage"
          MetricStat:
            Metric:
              Namespace: AWS/SQS
              MetricName: ApproximateAgeOfOldestMessage
              Dimensions:
                - Name: QueueName
                  Value: !GetAtt ReminderDeadLetterQueue.QueueName
            Period: 3600
            Stat: Maximum
      Threshold: 86400
      ComparisonOperator: GreaterThanThreshold
      EvaluationPeriods: 1
      DatapointsToAlarm: 1
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref ReminderNotificationTopic

  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-lambda-error-rate-high
      AlarmDescription: "High error rate in Send Reminder Lambda"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
      AlarmActions:
        - !Ref ReminderNotificationTopic

  OpenSearchCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${EnvironmentName}-opensearch-cpu-high
      AlarmDescription: "High CPU utilization in OpenSearch"
      MetricName: CPUUtilization
      Namespace: AWS/ES
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: DomainName
          Value: !Ref OpenSearchDomainName
        - Name: ClientId
          Value: !Ref AWS::AccountId
      AlarmActions:
        - !Ref ReminderNotificationTopic

  # SESVerifiedEmail:
  #   Type: AWS::SES::EmailIdentity
  #   Properties:
  #     EmailIdentity: !Ref EmailAddress

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub ${EnvironmentName}-voice-reminder-api
      Description: Voice Reminder API
      EndpointConfiguration:
        Types:
          - REGIONAL
      FailOnWarnings: true

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: !Ref EnvironmentName
    DependsOn:
      - HealthMethod

  HealthResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: health

  HealthMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref HealthResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        IntegrationHttpMethod: POST
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseTemplates:
              application/json: '{"status": "healthy", "timestamp": "$context.requestTime"}'
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty

  ApiGatewayUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: !Ref EnvironmentName
      UsagePlanName: !Sub ${EnvironmentName}-voice-reminder-usage-plan
      Throttle:
        BurstLimit: 100
        RateLimit: 50
      Quota:
        Limit: 10000
        Period: MONTH

  ApiGatewayApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub ${EnvironmentName}-voice-reminder-api-key
      Enabled: true
      StageKeys:
        - RestApiId: !Ref ApiGateway
          StageName: !Ref EnvironmentName

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: api

  ApiVersionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref ApiResource
      PathPart: v1

  RemindersResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref ApiVersionResource
      PathPart: reminders

  ApiGatewayCors:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref ApiGateway
      ResponseType: DEFAULT_4XX
      ResponseParameters:
        gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
        gatewayresponse.header.Access-Control-Allow-Headers: "'*'"

  ReminderNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${EnvironmentName}-reminder-notifications
      DisplayName: "Voice Reminder Notifications"
      Subscription:
        - Protocol: email
          Endpoint: !Ref EmailAddress

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${LambdaFunctionName}
      RetentionInDays: 30

  AppLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /${EnvironmentName}/reminder-app
      RetentionInDays: 30

  TranscribeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/transcribe/${EnvironmentName}
      RetentionInDays: 7

  ApiGatewayHealthResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: "health"

  SecretsManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/voice-reminder/secrets
      Description: Secrets for Voice Reminder application
      GenerateSecretString:
        SecretStringTemplate: '{"NLP_GRPC_KEY": "placeholder"}'
        GenerateStringKey: "SERVICE_TOKEN"
        PasswordLength: 32
        ExcludeCharacters: '"@/\'

  KMSCustomerManagedKey:
    Type: AWS::KMS::Key
    Properties:
      Description: KMS key for Voice Reminder encryption
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: key-default-1
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action: kms:*
            Resource: "*"
          - Sid: Allow Secrets Manager to use the key
            Effect: Allow
            Principal:
              Service: secretsmanager.amazonaws.com
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
          - Sid: Allow Lambda to use the key
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - kms:Decrypt
            Resource: "*"
            Condition:
              StringEquals:
                kms:ViaService: !Sub lambda.${AWS::Region}.amazonaws.com

  KMSCustomerManagedKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${EnvironmentName}-voice-reminder-key
      TargetKeyId: !Ref KMSCustomerManagedKey

  SecretsManagerSecretKMSAssociation:
    Type: AWS::SecretsManager::ResourcePolicy
    Properties:
      SecretId: !Ref SecretsManagerSecret
      ResourcePolicy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !GetAtt AppExecutionRole.Arn
            Action:
              - secretsmanager:GetSecretValue
              - secretsmanager:DescribeSecret
            Resource: "*"

  CertificateManagerCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub api.${EnvironmentName}.voice-reminder.example.com
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub api.${EnvironmentName}.voice-reminder.example.com
          HostedZoneId: ZONE_ID_IF_NEEDED

Outputs:
  AudioBucketName:
    Description: S3 Bucket for audio files
    Value: !Ref AudioBucket

  OpenSearchEndpoint:
    Description: OpenSearch Domain Endpoint
    Value: !GetAtt OpenSearchDomain.DomainEndpoint

  AppExecutionRoleArn:
    Description: IAM Role for Application
    Value: !GetAtt AppExecutionRole.Arn

  TranscribeServiceRoleArn:
    Description: IAM Role for Amazon Transcribe
    Value: !GetAtt TranscribeServiceRole.Arn

  SESVerifiedEmail:
    Description: Verified SES Email Address
    Value: !Ref EmailAddress

  S3BucketUrl:
    Description: S3 Bucket URL
    Value: !Sub s3://${AudioBucket}

  ApiGatewayUrl:
    Description: API Gateway URL
    Value: !Sub https://${ApiGateway}.execute-api.localhost.localstack.cloud:4566/${EnvironmentName}
