apiVersion: v1
kind: Service
metadata:
  name: nlp-service
  namespace: app
  labels:
    app: nlp-service
spec:
  selector:
    app: nlp-service
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
  type: ClusterIP