Vagrant.configure("2") do |config|
  config.vm.box = "amazonlinux2"  
  config.vm.hostname = "amazonlinux2"
  
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 2
    vb.name = "amazonlinux2-vm"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    yum update -y
    yum install -y git curl wget
  SHELL
  
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  config.vm.network "forwarded_port", guest: 8080, host: 8083
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8082, host: 8082
  
  config.vm.synced_folder ".", "/vagrant", type: "rsync"
  
  config.vm.boot_timeout = 600
  config.ssh.insert_key = false
end