apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: "${GRAFANA_USER:-admin}"
  GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_PASSWORD:-admin}"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secrets
  namespace: monitoring
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://postgres:${POSTGRES_PASSWORD_URLENCODED}@postgres.database:5432/voice_reminder?sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-exporter-secrets
  namespace: monitoring
type: Opaque
stringData:
  REDIS_ADDR: "redis://redis.database:6379"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_EXPORTER_SKIP_TLS_VERIFICATION: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudwatch-exporter-secrets
  namespace: monitoring
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-test}"
  AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-test}"
  AWS_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://localstack.cloud:4566"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-certs
  namespace: monitoring
type: Opaque
stringData:
  redis-key.pem: "${REDIS_KEY_PEM}"     # redis/certs/redis-key.pem
  redis.pem: "${REDIS_CERT_PEM}"        # redis/certs/redis.pem
  root-ca.pem: "${REDIS_CA_PEM}"        # redis/certs/root-ca.pem