# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import reminder_parser_pb2 as reminder__parser__pb2


class ReminderParserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseReminder = channel.unary_unary(
                '/reminderparser.ReminderParserService/ParseReminder',
                request_serializer=reminder__parser__pb2.ParseRequest.SerializeToString,
                response_deserializer=reminder__parser__pb2.ParseResponse.FromString,
                )
        self.HealthCheck = channel.unary_unary(
                '/reminderparser.ReminderParserService/HealthCheck',
                request_serializer=reminder__parser__pb2.HealthRequest.SerializeToString,
                response_deserializer=reminder__parser__pb2.HealthResponse.FromString,
                )


class ReminderParserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ParseReminder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReminderParserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseReminder': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseReminder,
                    request_deserializer=reminder__parser__pb2.ParseRequest.FromString,
                    response_serializer=reminder__parser__pb2.ParseResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=reminder__parser__pb2.HealthRequest.FromString,
                    response_serializer=reminder__parser__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reminderparser.ReminderParserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReminderParserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ParseReminder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reminderparser.ReminderParserService/ParseReminder',
            reminder__parser__pb2.ParseRequest.SerializeToString,
            reminder__parser__pb2.ParseResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/reminderparser.ReminderParserService/HealthCheck',
            reminder__parser__pb2.HealthRequest.SerializeToString,
            reminder__parser__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
