apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: cloud
  labels:
    app: localstack
    component: aws-emulation
spec:
  selector:
    app: localstack
  ports:
    - name: edge
      port: 4566
      targetPort: 4566
    - name: opensearch
      port: 4510
      targetPort: 4510
  type: ClusterIP