apiVersion: v1
kind: Secret
metadata:
  name: localstack-secrets
  namespace: cloud
type: Opaque
stringData:
  OPENSEARCH_ADMIN_PASSWORD: ${OPENSEARCH_ADMIN_PASSWORD}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: localstack-secrets-dir
  namespace: cloud
type: Opaque
stringData:
  OPENSEARCH_ADMIN_PASSWORD: ${OPENSEARCH_ADMIN_PASSWORD}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
  opensearch_password.txt: ${OPENSEARCH_ADMIN_PASSWORD}
  aws_access_key.txt: ${AWS_ACCESS_KEY_ID}
  aws_secret_key.txt: ${AWS_SECRET_ACCESS_KEY}