apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: database
type: Opaque
stringData:
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets-dir
  namespace: database
type: Opaque
stringData:
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
  postgres_user.txt: ${POSTGRES_USER}
  postgres_password.txt: ${POSTGRES_PASSWORD}
  postgres_db.txt: ${POSTGRES_DB}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: database
type: Opaque
stringData:
  REDIS_PASSWORD: ${REDIS_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-certs
  namespace: database
type: Opaque
stringData:
  redis-key.pem: ${REDIS_KEY_PEM}
  redis.pem: ${REDIS_CERT_PEM}
  root-ca.pem: ${REDIS_CA_PEM}