apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
  GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secrets
  namespace: monitoring
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD_URLENCODED}@postgres.database:5432/${POSTGRES_DB}?sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-exporter-secrets
  namespace: monitoring
type: Opaque
stringData:
  REDIS_ADDR: "redis://redis.database:6379"
  REDIS_PASSWORD: ${REDIS_PASSWORD}
  REDIS_EXPORTER_SKIP_TLS_VERIFICATION: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudwatch-exporter-secrets
  namespace: monitoring
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_REGION: ${AWS_REGION}
  AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL}
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-certs
  namespace: monitoring
type: Opaque
stringData:
  redis-key.pem: ${REDIS_KEY_PEM}
  redis.pem: ${REDIS_CERT_PEM}
  root-ca.pem: ${REDIS_CA_PEM}