apiVersion: v1
kind: Secret
metadata:
  name: opensearch-certs
  namespace: cloud
type: Opaque
stringData:
  root-ca.pem: ${OPENSEARCH_ROOT_CA}
  node.pem: ${OPENSEARCH_NODE_CERT}
  node-key.pem: ${OPENSEARCH_NODE_KEY}
  admin.pem: ${OPENSEARCH_ADMIN_CERT}
  admin-key.pem: ${OPENSEARCH_ADMIN_KEY}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-certs
  namespace: app
type: Opaque
stringData:
  root-ca.pem: ${OPENSEARCH_ROOT_CA}
---
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-certs
  namespace: monitoring
type: Opaque
stringData:
  root-ca.pem: ${OPENSEARCH_ROOT_CA}