apiVersion: v1
kind: Secret
metadata:
  name: reminder-app-secrets
  namespace: app
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  SMTP_USERNAME: losik2006@gmail.com
  FROM_EMAIL: losik2006@gmail.com
  NOTIFICATION_EMAIL: losik2006@gmail.com